version: '3.8'
services:
  sonarqube:
    image: sonarqube:community
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONARQUBE_TOKEN=1234567890
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    env_file:
      - ../.env

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
